const characters = [
  "Ludo Bagman",
  "Bathilda Bagshot",
  "Sirius Black",
  "Albus Dumbledore",
  "Harry Potter",
  "Hermione Granger",
  "Vernon Dursley",
  "Ron Weasley",
  "Cornelius Fudge",
  "Rubeus Hagrid ",
  "Viktor Krum",
  "Draco Malfoy",
  "Neville Longbottom",
  "Lucius Malfoy ",
  "Lord Voldemort",
  "Minerva McGonagall",
  "Peter Pettigrew",
  "James Potter",
  "Horace Slughorn ",
  "Moaning Myrtle",
  "Fred Weasley",
  "Dobby",
  "Hedwig",
  "Alastor Moody",
  "Remus Lupin",
  "Katie Bell",
  "Phineas Nigellus Black",
  "Amelia Bones",
  "Susan Bones",
  "Frank Bryce ",
];

export default characters;
