const characters = [
  "Ludo Bagman",
  "Bathilda Bagshot",
  "Sirius Black",
  "Albus Dumbledore",
  "Harry Potter",
  "Hermione Granger",
  "Vernon Dursley",
  "Ron Weasley",
  "Cornelius Fudge",
  "Rubeus Hagrid ",
  "Viktor Krum",
  "Draco Malfoy",
  "Neville Longbottom",
  "Lucius Malfoy ",
  "Lord Voldemort",
  "Minerva McGonagall",
  "Peter Pettigrew",
  "James Potter",
  "Horace Slughorn ",
  "Moaning Myrtle",
  "Fred Weasley",
  "Dobby",
  "Hedwig",
  "Alastor Moody",
  "Remus Lupin",
  "Katie Bell",
  "Phineas Nigellus Black",
  "Amelia Bones",
  "Susan Bones",
  "Frank Bryce",
  "Alecto Carrow",
  "Reginald Cattermole",
  "Cho Chang",
  "Crabbe",
  "Dennis Creevey",
  "Barty Crouch Sr",
  "Antonin Dolohov",
  "Petunia Dursley",
  "Dudley Dursley",
  "Arabella Figg",
  "Justin Finch-Fletchley",
  "Merope Gaunt",
  "Gellert Grindelwald",
  "Godric Gryffindor",
  "Mafalda Hopkirk",
  "Helga Hufflepuff",
  "Angelina Johnson",
  "Bellatrix Lestrange",
  "Gilderoy Lockhart",
  "Luna Lovegood",
  "Lucius Malfoy",
  "Padma Patil",
  "Poppy Pomfrey",
  "Lily Potter",
  "Severus Snape",
  "Pomona Sprout",
  "Rita Skeeter",
  "Oliver Wood",
  "Aragog",
  "Buckbeak",
  "Fluffy",
  "Kreacher",
  "Great Aunt Muriel",
  "Nagini",
  "Norbert",
  "Scabbers",
  "Molly Weasley",
  "Ginny Weasley",
  "Charlie Weasley",
  "Arthur Weasley",
  "Romilda Vane",
  "Dolores Umbridge",
  "Newt Scamander",
  "Sturgis Podmore",
  "Garrick Ollivander",
];

export default characters;
